# Generated by Django 4.2 on 2026-09-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
