# Generated by Django 4.2.7 on 2026-09-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0003_eventregistration_why_join'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulkrfq',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='bulkrfq',
            name='product_items',
        ),
        migrations.AddField(
            model_name='bulkrfq',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bulkrfq',
            name='product_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
