# Generated by Django 4.2.7 on 2026-09-27 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['id'], 'verbose_name_plural': 'Staff'},
        ),
    ]
