# Generated by Django 4.2.7 on 2026-09-24 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
    ]
