# Generated by Django 4.2.7 on 2026-10-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_service_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero-slides/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
